# Default Ubigia build and test pipeline. 
variables:
  buildDisplayName: 'EtAlii.Ubigia'
  sonarQubeProject: 'EtAlii.Ubigia'
  timeoutInMinutes: 960
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Debug'

trigger:
  - master

name: ${{ variables.buildDisplayName }}

jobs:
  - job: 'buildAndTest'
    displayName: 'Build and Test'
    timeoutInMinutes: ${{ variables.timeoutInMinutes }}
    pool:
      name: 'Avalon agent pool'
      demands:
        #- SpecialSoftware # Check if SpecialSoftware capability exists
        # Check if Agent.OS == Windows_NT
        - Agent.OS -equals Windows_NT 
      #vmImage: 'ubuntu-latest'    # For Docker.
      #vmImage: 'windows-latest'   # For Windows.
    steps:
    
# BUILD
      - task: UseDotNet@2
        displayName: 'Use: dotnet SDK 3.1.403'
        inputs:
          packageType: 'sdk'
          version: '3.1.403'

      - task: NugetToolInstaller@1

      - task: SonarQubePrepare@4
        displayName: 'SonarQube: prepare'
        inputs:
          SonarQube: 'Avalon SonarQube'
          scannerMode: 'MSBuild'
          projectKey: ${{ variables.sonarQubeProject }}
          extraProperties: |
            # sonar.cs.vscoveragexml.reportsPaths=$(Build.SourcesDirectory)/**/*.coveragexml
            sonar.cs.opencover.reportsPaths=$(Build.SourcesDirectory)/**/TestResults/**/coverage.opencover.xml
            sonar.coverage.exclusions=”**/*.Tests.cs”

      - task: DotNetCoreCLI@2
        displayName: 'Run: dotnet restore'
        inputs:
          command: 'restore'
          projects: |
            **/*.csproj
            !**/ProjectToExclude.csproj
          feedsToUse: config
          nugetConfigPath: NuGet.config

      - task: DotNetCoreCLI@2
        displayName: 'Run: dotnet build'
        inputs:
          command: 'build'
          projects: |
            **/*.sln
            !**/StorageBrowser.csproj
          arguments: ' --no-restore --configuration $(BuildConfiguration) /p:UbigiaIsRunningOnBuildAgent=true -nodeReuse:false -maxCpuCount:8'

# TEST
      - task: DotNetCoreCLI@2
        displayName: 'Run: dotnet test'
        inputs:
          command: test
          # **/EtAlii.Ubigia.Api.Logical.WebApi.Tests.csproj
          # **/EtAlii.Ubigia.Api.Fabric.WebApi.Tests.csproj
          # **/EtAlii.Ubigia.Api.Functional.Scripting.GraphSL.WebApi.Tests.csproj
          # **/*.Tests.csproj
          # !**/*.WebApi.Tests.csproj
          # **/EtAlii.Ubigia.Api.Transport.WebApi.csproj
          # **/EtAlii.Ubigia.Api.Functional.Scripting.GraphQL.WebApi.Tests.csproj
          # **/EtAlii.Ubigia.Api.Functional.Scripting.GraphSL.WebApi.Tests.csproj
          # **/EtAlii.Ubigia.Api.Logical.WebApi.Tests.csproj
          #  **/*.Tests.csproj
          projects: |
           **/EtAlii.Ubigia.Api.Functional.Scripting.GraphQL.*.Tests.csproj
          arguments: '/p:SolutionDir=$(Build.SourcesDirectory) --no-restore --no-build --collect:"XPlat Code Coverage" -nodeReuse:false -maxCpuCount:8 -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover'
        continueOnError: true

      - task: SonarQubeAnalyze@4
        displayName: 'SonarQube: analyse'


      - task: SonarQubePublish@4
        displayName: 'SonarQube: publish'
        inputs:
          pollingTimeoutSec: '300'

# PUBLISH
#      - task: NuGetAuthenticate@0
#        displayName: 'Run: nuget authenticate'
#
#      - script: dotnet nuget push --api-key AzureArtifacts --skip-duplicate --source ${{ variables.packageFeedUrl }} **/*.nupkg
#        displayName: 'Run: dotnet nuget push'

