// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContentDefinition.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EtAlii.Ubigia.Api.Transport.Grpc {

  /// <summary>Holder for reflection information generated from ContentDefinition.proto</summary>
  public static partial class ContentDefinitionReflection {

    #region Descriptor
    /// <summary>File descriptor for ContentDefinition.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ContentDefinitionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdDb250ZW50RGVmaW5pdGlvbi5wcm90bxIgRXRBbGlpLlViaWdpYS5BcGku",
            "VHJhbnNwb3J0LkdycGMaDF9Nb2RlbC5wcm90byIaChhDb250ZW50RGVmaW5p",
            "dGlvblJlcXVlc3QiGwoZQ29udGVudERlZmluaXRpb25SZXNwb25zZTKuBAoc",
            "Q29udGVudERlZmluaXRpb25HcnBjU2VydmljZRKAAQoDR2V0EjouRXRBbGlp",
            "LlViaWdpYS5BcGkuVHJhbnNwb3J0LkdycGMuQ29udGVudERlZmluaXRpb25S",
            "ZXF1ZXN0GjsuRXRBbGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0LkdycGMuQ29u",
            "dGVudERlZmluaXRpb25SZXNwb25zZSIAEoEBCgRQb3N0EjouRXRBbGlpLlVi",
            "aWdpYS5BcGkuVHJhbnNwb3J0LkdycGMuQ29udGVudERlZmluaXRpb25SZXF1",
            "ZXN0GjsuRXRBbGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0LkdycGMuQ29udGVu",
            "dERlZmluaXRpb25SZXNwb25zZSIAEoABCgNQdXQSOi5FdEFsaWkuVWJpZ2lh",
            "LkFwaS5UcmFuc3BvcnQuR3JwYy5Db250ZW50RGVmaW5pdGlvblJlcXVlc3Qa",
            "Oy5FdEFsaWkuVWJpZ2lhLkFwaS5UcmFuc3BvcnQuR3JwYy5Db250ZW50RGVm",
            "aW5pdGlvblJlc3BvbnNlIgASgwEKBkRlbGV0ZRI6LkV0QWxpaS5VYmlnaWEu",
            "QXBpLlRyYW5zcG9ydC5HcnBjLkNvbnRlbnREZWZpbml0aW9uUmVxdWVzdBo7",
            "LkV0QWxpaS5VYmlnaWEuQXBpLlRyYW5zcG9ydC5HcnBjLkNvbnRlbnREZWZp",
            "bml0aW9uUmVzcG9uc2UiAEJYCiBFdEFsaWkuVWJpZ2lhLkFwaS5UcmFuc3Bv",
            "cnQuR3JwY0IGVWJpZ2lhUAGiAgZVYmlnaWGqAiBFdEFsaWkuVWJpZ2lhLkFw",
            "aS5UcmFuc3BvcnQuR3JwY2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EtAlii.Ubigia.Api.Transport.Grpc.ModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EtAlii.Ubigia.Api.Transport.Grpc.ContentDefinitionRequest), global::EtAlii.Ubigia.Api.Transport.Grpc.ContentDefinitionRequest.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EtAlii.Ubigia.Api.Transport.Grpc.ContentDefinitionResponse), global::EtAlii.Ubigia.Api.Transport.Grpc.ContentDefinitionResponse.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ContentDefinitionRequest : pb::IMessage<ContentDefinitionRequest> {
    private static readonly pb::MessageParser<ContentDefinitionRequest> _parser = new pb::MessageParser<ContentDefinitionRequest>(() => new ContentDefinitionRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ContentDefinitionRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EtAlii.Ubigia.Api.Transport.Grpc.ContentDefinitionReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContentDefinitionRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContentDefinitionRequest(ContentDefinitionRequest other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContentDefinitionRequest Clone() {
      return new ContentDefinitionRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ContentDefinitionRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ContentDefinitionRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ContentDefinitionRequest other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed partial class ContentDefinitionResponse : pb::IMessage<ContentDefinitionResponse> {
    private static readonly pb::MessageParser<ContentDefinitionResponse> _parser = new pb::MessageParser<ContentDefinitionResponse>(() => new ContentDefinitionResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ContentDefinitionResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EtAlii.Ubigia.Api.Transport.Grpc.ContentDefinitionReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContentDefinitionResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContentDefinitionResponse(ContentDefinitionResponse other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ContentDefinitionResponse Clone() {
      return new ContentDefinitionResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ContentDefinitionResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ContentDefinitionResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ContentDefinitionResponse other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
