// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Entry.proto
// </auto-generated>
// Original file comments:
//
// Copyright 2018 Peter Vrenken.
//
#pragma warning disable 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol {
  /// <summary>
  /// The Entry Grpc service definition.
  /// </summary>
  public static partial class EntryGrpcService
  {
    static readonly string __ServiceName = "EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryGrpcService";

    static readonly grpc::Marshaller<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest> __Marshaller_EntrySingleRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> __Marshaller_EntrySingleResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleRequest> __Marshaller_EntryMultipleRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse> __Marshaller_EntryMultipleResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryRelatedRequest> __Marshaller_EntryRelatedRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryRelatedRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPostRequest> __Marshaller_EntryPostRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPostRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPutRequest> __Marshaller_EntryPutRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPutRequest.Parser.ParseFrom);

    static readonly grpc::Method<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest, global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> __Method_GetSingle = new grpc::Method<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest, global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSingle",
        __Marshaller_EntrySingleRequest,
        __Marshaller_EntrySingleResponse);

    static readonly grpc::Method<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleRequest, global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse> __Method_GetMultiple = new grpc::Method<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleRequest, global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMultiple",
        __Marshaller_EntryMultipleRequest,
        __Marshaller_EntryMultipleResponse);

    static readonly grpc::Method<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryRelatedRequest, global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse> __Method_GetRelated = new grpc::Method<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryRelatedRequest, global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRelated",
        __Marshaller_EntryRelatedRequest,
        __Marshaller_EntryMultipleResponse);

    static readonly grpc::Method<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPostRequest, global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> __Method_Post = new grpc::Method<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPostRequest, global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Post",
        __Marshaller_EntryPostRequest,
        __Marshaller_EntrySingleResponse);

    static readonly grpc::Method<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPutRequest, global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> __Method_Put = new grpc::Method<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPutRequest, global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Put",
        __Marshaller_EntryPutRequest,
        __Marshaller_EntrySingleResponse);

    static readonly grpc::Method<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest, global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> __Method_Delete = new grpc::Method<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest, global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Delete",
        __Marshaller_EntrySingleRequest,
        __Marshaller_EntrySingleResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of EntryGrpcService</summary>
    public abstract partial class EntryGrpcServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> GetSingle(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse> GetMultiple(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse> GetRelated(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryRelatedRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> Post(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPostRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> Put(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPutRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> Delete(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for EntryGrpcService</summary>
    public partial class EntryGrpcServiceClient : grpc::ClientBase<EntryGrpcServiceClient>
    {
      /// <summary>Creates a new client for EntryGrpcService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public EntryGrpcServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for EntryGrpcService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public EntryGrpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected EntryGrpcServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected EntryGrpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse GetSingle(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSingle(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse GetSingle(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSingle, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> GetSingleAsync(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSingleAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> GetSingleAsync(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSingle, null, options, request);
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse GetMultiple(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMultiple(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse GetMultiple(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMultiple, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse> GetMultipleAsync(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMultipleAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse> GetMultipleAsync(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMultiple, null, options, request);
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse GetRelated(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryRelatedRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRelated(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse GetRelated(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryRelatedRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRelated, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse> GetRelatedAsync(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryRelatedRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRelatedAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryMultipleResponse> GetRelatedAsync(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryRelatedRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRelated, null, options, request);
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse Post(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPostRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Post(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse Post(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPostRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Post, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> PostAsync(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPostRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PostAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> PostAsync(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPostRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Post, null, options, request);
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse Put(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPutRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Put(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse Put(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPutRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Put, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> PutAsync(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPutRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PutAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> PutAsync(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntryPutRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Put, null, options, request);
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse Delete(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Delete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse Delete(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Delete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> DeleteAsync(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleResponse> DeleteAsync(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.EntrySingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Delete, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override EntryGrpcServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EntryGrpcServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(EntryGrpcServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetSingle, serviceImpl.GetSingle)
          .AddMethod(__Method_GetMultiple, serviceImpl.GetMultiple)
          .AddMethod(__Method_GetRelated, serviceImpl.GetRelated)
          .AddMethod(__Method_Post, serviceImpl.Post)
          .AddMethod(__Method_Put, serviceImpl.Put)
          .AddMethod(__Method_Delete, serviceImpl.Delete).Build();
    }

  }
}
#endregion
