// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Space.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol {

  /// <summary>Holder for reflection information generated from Space.proto</summary>
  public static partial class SpaceReflection {

    #region Descriptor
    /// <summary>File descriptor for Space.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SpaceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtTcGFjZS5wcm90bxItRXRBbGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0Lkdy",
            "cGMuV2lyZVByb3RvY29sGgxfTW9kZWwucHJvdG8iuwEKElNwYWNlU2luZ2xl",
            "UmVxdWVzdBJBCgJJZBgCIAEoCzIzLkV0QWxpaS5VYmlnaWEuQXBpLlRyYW5z",
            "cG9ydC5HcnBjLldpcmVQcm90b2NvbC5HdWlkSAASDgoETmFtZRgDIAEoCUgA",
            "EkUKBVNwYWNlGAQgASgLMjQuRXRBbGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0",
            "LkdycGMuV2lyZVByb3RvY29sLlNwYWNlSABCCwoJU2VsZWN0aW9uIl0KFlNw",
            "YWNlUG9zdFNpbmdsZVJlcXVlc3QSQwoFU3BhY2UYAiABKAsyNC5FdEFsaWku",
            "VWJpZ2lhLkFwaS5UcmFuc3BvcnQuR3JwYy5XaXJlUHJvdG9jb2wuU3BhY2Ui",
            "FgoUU3BhY2VNdWx0aXBsZVJlcXVlc3QiWgoTU3BhY2VTaW5nbGVSZXNwb25z",
            "ZRJDCgVTcGFjZRgBIAEoCzI0LkV0QWxpaS5VYmlnaWEuQXBpLlRyYW5zcG9y",
            "dC5HcnBjLldpcmVQcm90b2NvbC5TcGFjZSJdChVTcGFjZU11bHRpcGxlUmVz",
            "cG9uc2USRAoGU3BhY2VzGAEgAygLMjQuRXRBbGlpLlViaWdpYS5BcGkuVHJh",
            "bnNwb3J0LkdycGMuV2lyZVByb3RvY29sLlNwYWNlMoEGChBTcGFjZUdycGNT",
            "ZXJ2aWNlEpQBCglHZXRTaW5nbGUSQS5FdEFsaWkuVWJpZ2lhLkFwaS5UcmFu",
            "c3BvcnQuR3JwYy5XaXJlUHJvdG9jb2wuU3BhY2VTaW5nbGVSZXF1ZXN0GkIu",
            "RXRBbGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0LkdycGMuV2lyZVByb3RvY29s",
            "LlNwYWNlU2luZ2xlUmVzcG9uc2UiABKaAQoLR2V0TXVsdGlwbGUSQy5FdEFs",
            "aWkuVWJpZ2lhLkFwaS5UcmFuc3BvcnQuR3JwYy5XaXJlUHJvdG9jb2wuU3Bh",
            "Y2VNdWx0aXBsZVJlcXVlc3QaRC5FdEFsaWkuVWJpZ2lhLkFwaS5UcmFuc3Bv",
            "cnQuR3JwYy5XaXJlUHJvdG9jb2wuU3BhY2VNdWx0aXBsZVJlc3BvbnNlIgAS",
            "kwEKBFBvc3QSRS5FdEFsaWkuVWJpZ2lhLkFwaS5UcmFuc3BvcnQuR3JwYy5X",
            "aXJlUHJvdG9jb2wuU3BhY2VQb3N0U2luZ2xlUmVxdWVzdBpCLkV0QWxpaS5V",
            "YmlnaWEuQXBpLlRyYW5zcG9ydC5HcnBjLldpcmVQcm90b2NvbC5TcGFjZVNp",
            "bmdsZVJlc3BvbnNlIgASjgEKA1B1dBJBLkV0QWxpaS5VYmlnaWEuQXBpLlRy",
            "YW5zcG9ydC5HcnBjLldpcmVQcm90b2NvbC5TcGFjZVNpbmdsZVJlcXVlc3Qa",
            "Qi5FdEFsaWkuVWJpZ2lhLkFwaS5UcmFuc3BvcnQuR3JwYy5XaXJlUHJvdG9j",
            "b2wuU3BhY2VTaW5nbGVSZXNwb25zZSIAEpEBCgZEZWxldGUSQS5FdEFsaWku",
            "VWJpZ2lhLkFwaS5UcmFuc3BvcnQuR3JwYy5XaXJlUHJvdG9jb2wuU3BhY2VT",
            "aW5nbGVSZXF1ZXN0GkIuRXRBbGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0Lkdy",
            "cGMuV2lyZVByb3RvY29sLlNwYWNlU2luZ2xlUmVzcG9uc2UiAEJyCi1FdEFs",
            "aWkuVWJpZ2lhLkFwaS5UcmFuc3BvcnQuR3JwYy5XaXJlUHJvdG9jb2xCBlVi",
            "aWdpYVABogIGVWJpZ2lhqgItRXRBbGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0",
            "LkdycGMuV2lyZVByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.ModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpaceSingleRequest), global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpaceSingleRequest.Parser, new[]{ "Id", "Name", "Space" }, new[]{ "Selection" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpacePostSingleRequest), global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpacePostSingleRequest.Parser, new[]{ "Space" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpaceMultipleRequest), global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpaceMultipleRequest.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpaceSingleResponse), global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpaceSingleResponse.Parser, new[]{ "Space" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpaceMultipleResponse), global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpaceMultipleResponse.Parser, new[]{ "Spaces" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SpaceSingleRequest : pb::IMessage<SpaceSingleRequest> {
    private static readonly pb::MessageParser<SpaceSingleRequest> _parser = new pb::MessageParser<SpaceSingleRequest>(() => new SpaceSingleRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SpaceSingleRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpaceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpaceSingleRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpaceSingleRequest(SpaceSingleRequest other) : this() {
      switch (other.SelectionCase) {
        case SelectionOneofCase.Id:
          Id = other.Id.Clone();
          break;
        case SelectionOneofCase.Name:
          Name = other.Name;
          break;
        case SelectionOneofCase.Space:
          Space = other.Space.Clone();
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpaceSingleRequest Clone() {
      return new SpaceSingleRequest(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Guid Id {
      get { return selectionCase_ == SelectionOneofCase.Id ? (global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Guid) selection_ : null; }
      set {
        selection_ = value;
        selectionCase_ = value == null ? SelectionOneofCase.None : SelectionOneofCase.Id;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return selectionCase_ == SelectionOneofCase.Name ? (string) selection_ : ""; }
      set {
        selection_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        selectionCase_ = SelectionOneofCase.Name;
      }
    }

    /// <summary>Field number for the "Space" field.</summary>
    public const int SpaceFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space Space {
      get { return selectionCase_ == SelectionOneofCase.Space ? (global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space) selection_ : null; }
      set {
        selection_ = value;
        selectionCase_ = value == null ? SelectionOneofCase.None : SelectionOneofCase.Space;
      }
    }

    private object selection_;
    /// <summary>Enum of possible cases for the "Selection" oneof.</summary>
    public enum SelectionOneofCase {
      None = 0,
      Id = 2,
      Name = 3,
      Space = 4,
    }
    private SelectionOneofCase selectionCase_ = SelectionOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SelectionOneofCase SelectionCase {
      get { return selectionCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSelection() {
      selectionCase_ = SelectionOneofCase.None;
      selection_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SpaceSingleRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SpaceSingleRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(Space, other.Space)) return false;
      if (SelectionCase != other.SelectionCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (selectionCase_ == SelectionOneofCase.Id) hash ^= Id.GetHashCode();
      if (selectionCase_ == SelectionOneofCase.Name) hash ^= Name.GetHashCode();
      if (selectionCase_ == SelectionOneofCase.Space) hash ^= Space.GetHashCode();
      hash ^= (int) selectionCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (selectionCase_ == SelectionOneofCase.Id) {
        output.WriteRawTag(18);
        output.WriteMessage(Id);
      }
      if (selectionCase_ == SelectionOneofCase.Name) {
        output.WriteRawTag(26);
        output.WriteString(Name);
      }
      if (selectionCase_ == SelectionOneofCase.Space) {
        output.WriteRawTag(34);
        output.WriteMessage(Space);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (selectionCase_ == SelectionOneofCase.Id) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (selectionCase_ == SelectionOneofCase.Name) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (selectionCase_ == SelectionOneofCase.Space) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Space);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SpaceSingleRequest other) {
      if (other == null) {
        return;
      }
      switch (other.SelectionCase) {
        case SelectionOneofCase.Id:
          if (Id == null) {
            Id = new global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Guid();
          }
          Id.MergeFrom(other.Id);
          break;
        case SelectionOneofCase.Name:
          Name = other.Name;
          break;
        case SelectionOneofCase.Space:
          if (Space == null) {
            Space = new global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space();
          }
          Space.MergeFrom(other.Space);
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 18: {
            global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Guid subBuilder = new global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Guid();
            if (selectionCase_ == SelectionOneofCase.Id) {
              subBuilder.MergeFrom(Id);
            }
            input.ReadMessage(subBuilder);
            Id = subBuilder;
            break;
          }
          case 26: {
            Name = input.ReadString();
            break;
          }
          case 34: {
            global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space subBuilder = new global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space();
            if (selectionCase_ == SelectionOneofCase.Space) {
              subBuilder.MergeFrom(Space);
            }
            input.ReadMessage(subBuilder);
            Space = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class SpacePostSingleRequest : pb::IMessage<SpacePostSingleRequest> {
    private static readonly pb::MessageParser<SpacePostSingleRequest> _parser = new pb::MessageParser<SpacePostSingleRequest>(() => new SpacePostSingleRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SpacePostSingleRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpaceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpacePostSingleRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpacePostSingleRequest(SpacePostSingleRequest other) : this() {
      Space = other.space_ != null ? other.Space.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpacePostSingleRequest Clone() {
      return new SpacePostSingleRequest(this);
    }

    /// <summary>Field number for the "Space" field.</summary>
    public const int SpaceFieldNumber = 2;
    private global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space space_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space Space {
      get { return space_; }
      set {
        space_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SpacePostSingleRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SpacePostSingleRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Space, other.Space)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (space_ != null) hash ^= Space.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (space_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Space);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (space_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Space);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SpacePostSingleRequest other) {
      if (other == null) {
        return;
      }
      if (other.space_ != null) {
        if (space_ == null) {
          space_ = new global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space();
        }
        Space.MergeFrom(other.Space);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 18: {
            if (space_ == null) {
              space_ = new global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space();
            }
            input.ReadMessage(space_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SpaceMultipleRequest : pb::IMessage<SpaceMultipleRequest> {
    private static readonly pb::MessageParser<SpaceMultipleRequest> _parser = new pb::MessageParser<SpaceMultipleRequest>(() => new SpaceMultipleRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SpaceMultipleRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpaceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpaceMultipleRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpaceMultipleRequest(SpaceMultipleRequest other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpaceMultipleRequest Clone() {
      return new SpaceMultipleRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SpaceMultipleRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SpaceMultipleRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SpaceMultipleRequest other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  public sealed partial class SpaceSingleResponse : pb::IMessage<SpaceSingleResponse> {
    private static readonly pb::MessageParser<SpaceSingleResponse> _parser = new pb::MessageParser<SpaceSingleResponse>(() => new SpaceSingleResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SpaceSingleResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpaceReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpaceSingleResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpaceSingleResponse(SpaceSingleResponse other) : this() {
      Space = other.space_ != null ? other.Space.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpaceSingleResponse Clone() {
      return new SpaceSingleResponse(this);
    }

    /// <summary>Field number for the "Space" field.</summary>
    public const int SpaceFieldNumber = 1;
    private global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space space_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space Space {
      get { return space_; }
      set {
        space_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SpaceSingleResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SpaceSingleResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Space, other.Space)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (space_ != null) hash ^= Space.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (space_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Space);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (space_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Space);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SpaceSingleResponse other) {
      if (other == null) {
        return;
      }
      if (other.space_ != null) {
        if (space_ == null) {
          space_ = new global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space();
        }
        Space.MergeFrom(other.Space);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (space_ == null) {
              space_ = new global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space();
            }
            input.ReadMessage(space_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class SpaceMultipleResponse : pb::IMessage<SpaceMultipleResponse> {
    private static readonly pb::MessageParser<SpaceMultipleResponse> _parser = new pb::MessageParser<SpaceMultipleResponse>(() => new SpaceMultipleResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SpaceMultipleResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.SpaceReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpaceMultipleResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpaceMultipleResponse(SpaceMultipleResponse other) : this() {
      spaces_ = other.spaces_.Clone();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SpaceMultipleResponse Clone() {
      return new SpaceMultipleResponse(this);
    }

    /// <summary>Field number for the "Spaces" field.</summary>
    public const int SpacesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space> _repeated_spaces_codec
        = pb::FieldCodec.ForMessage(10, global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space.Parser);
    private readonly pbc::RepeatedField<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space> spaces_ = new pbc::RepeatedField<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::EtAlii.Ubigia.Api.Transport.Grpc.WireProtocol.Space> Spaces {
      get { return spaces_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SpaceMultipleResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SpaceMultipleResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!spaces_.Equals(other.spaces_)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= spaces_.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      spaces_.WriteTo(output, _repeated_spaces_codec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += spaces_.CalculateSize(_repeated_spaces_codec);
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SpaceMultipleResponse other) {
      if (other == null) {
        return;
      }
      spaces_.Add(other.spaces_);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            spaces_.AddEntriesFrom(input, _repeated_spaces_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
