query data  
{ 
    person @nodes(path:"person:Stark/Tony")
    {
        name @id,
        lastName @id(path:"\\.Type=FamilyName")
        friends @nodes(path:"/Friends/") 
        { 
            name @id
            nickname
        } 
    }
}