#Stage 1
#FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
#
#WORKDIR /app
#
#COPY *.csproj ./
#
#RUN dotnet restore
#
#COPY . ./
#
#RUN dotnet publish -c Release -o out

# Stage 2
FROM mcr.microsoft.com/dotnet/core/aspnet:5.0

RUN apt-get update && apt-get install -y supervisor && apt-get install -y openssh-server && echo "root:Root123!" | chpasswd

RUN mkdir -p /var/log/supervisor /run/sshd

COPY sshd_config /etc/ssh/
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

#WORKDIR /app
#COPY --from=build /app/out .

EXPOSE 64000 64001 63999

ENTRYPOINT ["/usr/bin/supervisord"]
