// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Storage.proto
// </auto-generated>
// Original file comments:
//
// Copyright 2018 Peter Vrenken.
//
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol {
  /// <summary>
  /// The Storage Grpc service definition.
  /// </summary>
  public static partial class StorageGrpcService
  {
    static readonly string __ServiceName = "EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageGrpcService";

    static readonly grpc::Marshaller<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest> __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageSingleRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageSingleResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleRequest> __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageMultipleRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleResponse> __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageMultipleResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> __Method_GetSingle = new grpc::Method<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSingle",
        __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageSingleRequest,
        __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageSingleResponse);

    static readonly grpc::Method<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleResponse> __Method_GetMultiple = new grpc::Method<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetMultiple",
        __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageMultipleRequest,
        __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageMultipleResponse);

    static readonly grpc::Method<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> __Method_GetLocal = new grpc::Method<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetLocal",
        __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageSingleRequest,
        __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageSingleResponse);

    static readonly grpc::Method<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> __Method_Post = new grpc::Method<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Post",
        __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageSingleRequest,
        __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageSingleResponse);

    static readonly grpc::Method<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> __Method_Put = new grpc::Method<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Put",
        __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageSingleRequest,
        __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageSingleResponse);

    static readonly grpc::Method<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> __Method_Delete = new grpc::Method<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Delete",
        __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageSingleRequest,
        __Marshaller_EtAlii_Ubigia_Api_Transport_Management_Grpc_WireProtocol_StorageSingleResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of StorageGrpcService</summary>
    public abstract partial class StorageGrpcServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> GetSingle(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleResponse> GetMultiple(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> GetLocal(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> Post(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> Put(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> Delete(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for StorageGrpcService</summary>
    public partial class StorageGrpcServiceClient : grpc::ClientBase<StorageGrpcServiceClient>
    {
      /// <summary>Creates a new client for StorageGrpcService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public StorageGrpcServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for StorageGrpcService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public StorageGrpcServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected StorageGrpcServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected StorageGrpcServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse GetSingle(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSingle(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse GetSingle(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSingle, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> GetSingleAsync(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSingleAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> GetSingleAsync(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSingle, null, options, request);
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleResponse GetMultiple(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMultiple(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleResponse GetMultiple(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetMultiple, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleResponse> GetMultipleAsync(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetMultipleAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleResponse> GetMultipleAsync(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetMultiple, null, options, request);
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse GetLocal(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLocal(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse GetLocal(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetLocal, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> GetLocalAsync(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetLocalAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> GetLocalAsync(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetLocal, null, options, request);
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse Post(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Post(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse Post(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Post, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> PostAsync(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PostAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> PostAsync(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Post, null, options, request);
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse Put(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Put(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse Put(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Put, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> PutAsync(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PutAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> PutAsync(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Put, null, options, request);
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse Delete(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Delete(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse Delete(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Delete, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> DeleteAsync(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse> DeleteAsync(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Delete, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override StorageGrpcServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new StorageGrpcServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(StorageGrpcServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetSingle, serviceImpl.GetSingle)
          .AddMethod(__Method_GetMultiple, serviceImpl.GetMultiple)
          .AddMethod(__Method_GetLocal, serviceImpl.GetLocal)
          .AddMethod(__Method_Post, serviceImpl.Post)
          .AddMethod(__Method_Put, serviceImpl.Put)
          .AddMethod(__Method_Delete, serviceImpl.Delete).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, StorageGrpcServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GetSingle, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse>(serviceImpl.GetSingle));
      serviceBinder.AddMethod(__Method_GetMultiple, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleResponse>(serviceImpl.GetMultiple));
      serviceBinder.AddMethod(__Method_GetLocal, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse>(serviceImpl.GetLocal));
      serviceBinder.AddMethod(__Method_Post, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse>(serviceImpl.Post));
      serviceBinder.AddMethod(__Method_Put, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse>(serviceImpl.Put));
      serviceBinder.AddMethod(__Method_Delete, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse>(serviceImpl.Delete));
    }

  }
}
#endregion
