// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Storage.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EtAlii.Ubigia.Api.Transport.Management.Grpc {

  /// <summary>Holder for reflection information generated from Storage.proto</summary>
  public static partial class StorageReflection {

    #region Descriptor
    /// <summary>File descriptor for Storage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StorageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1TdG9yYWdlLnByb3RvEitFdEFsaWkuVWJpZ2lhLkFwaS5UcmFuc3BvcnQu",
            "TWFuYWdlbWVudC5HcnBjGgxfTW9kZWwucHJvdG8iTwoOU3RvcmFnZVJlcXVl",
            "c3QSPQoCSWQYASABKAsyMS5FdEFsaWkuVWJpZ2lhLkFwaS5UcmFuc3BvcnQu",
            "TWFuYWdlbWVudC5HcnBjLkd1aWQiWAoPU3RvcmFnZVJlc3BvbnNlEkUKB1N0",
            "b3JhZ2UYASABKAsyNC5FdEFsaWkuVWJpZ2lhLkFwaS5UcmFuc3BvcnQuTWFu",
            "YWdlbWVudC5HcnBjLlN0b3JhZ2UyrAQKElN0b3JhZ2VHcnBjU2VydmljZRKC",
            "AQoDR2V0EjsuRXRBbGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0Lk1hbmFnZW1l",
            "bnQuR3JwYy5TdG9yYWdlUmVxdWVzdBo8LkV0QWxpaS5VYmlnaWEuQXBpLlRy",
            "YW5zcG9ydC5NYW5hZ2VtZW50LkdycGMuU3RvcmFnZVJlc3BvbnNlIgASgwEK",
            "BFBvc3QSOy5FdEFsaWkuVWJpZ2lhLkFwaS5UcmFuc3BvcnQuTWFuYWdlbWVu",
            "dC5HcnBjLlN0b3JhZ2VSZXF1ZXN0GjwuRXRBbGlpLlViaWdpYS5BcGkuVHJh",
            "bnNwb3J0Lk1hbmFnZW1lbnQuR3JwYy5TdG9yYWdlUmVzcG9uc2UiABKCAQoD",
            "UHV0EjsuRXRBbGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0Lk1hbmFnZW1lbnQu",
            "R3JwYy5TdG9yYWdlUmVxdWVzdBo8LkV0QWxpaS5VYmlnaWEuQXBpLlRyYW5z",
            "cG9ydC5NYW5hZ2VtZW50LkdycGMuU3RvcmFnZVJlc3BvbnNlIgAShQEKBkRl",
            "bGV0ZRI7LkV0QWxpaS5VYmlnaWEuQXBpLlRyYW5zcG9ydC5NYW5hZ2VtZW50",
            "LkdycGMuU3RvcmFnZVJlcXVlc3QaPC5FdEFsaWkuVWJpZ2lhLkFwaS5UcmFu",
            "c3BvcnQuTWFuYWdlbWVudC5HcnBjLlN0b3JhZ2VSZXNwb25zZSIAQm4KK0V0",
            "QWxpaS5VYmlnaWEuQXBpLlRyYW5zcG9ydC5NYW5hZ2VtZW50LkdycGNCBlVi",
            "aWdpYVABogIGVWJpZ2lhqgIrRXRBbGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0",
            "Lk1hbmFnZW1lbnQuR3JwY2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EtAlii.Ubigia.Api.Transport.Management.Grpc.ModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.StorageRequest), global::EtAlii.Ubigia.Api.Transport.Management.Grpc.StorageRequest.Parser, new[]{ "Id" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.StorageResponse), global::EtAlii.Ubigia.Api.Transport.Management.Grpc.StorageResponse.Parser, new[]{ "Storage" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StorageRequest : pb::IMessage<StorageRequest> {
    private static readonly pb::MessageParser<StorageRequest> _parser = new pb::MessageParser<StorageRequest>(() => new StorageRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StorageRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EtAlii.Ubigia.Api.Transport.Management.Grpc.StorageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageRequest(StorageRequest other) : this() {
      Id = other.id_ != null ? other.Id.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageRequest Clone() {
      return new StorageRequest(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::EtAlii.Ubigia.Api.Transport.Management.Grpc.Guid id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EtAlii.Ubigia.Api.Transport.Management.Grpc.Guid Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StorageRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StorageRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (id_ != null) hash ^= Id.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (id_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (id_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StorageRequest other) {
      if (other == null) {
        return;
      }
      if (other.id_ != null) {
        if (id_ == null) {
          id_ = new global::EtAlii.Ubigia.Api.Transport.Management.Grpc.Guid();
        }
        Id.MergeFrom(other.Id);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (id_ == null) {
              id_ = new global::EtAlii.Ubigia.Api.Transport.Management.Grpc.Guid();
            }
            input.ReadMessage(id_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class StorageResponse : pb::IMessage<StorageResponse> {
    private static readonly pb::MessageParser<StorageResponse> _parser = new pb::MessageParser<StorageResponse>(() => new StorageResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StorageResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EtAlii.Ubigia.Api.Transport.Management.Grpc.StorageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageResponse(StorageResponse other) : this() {
      Storage = other.storage_ != null ? other.Storage.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageResponse Clone() {
      return new StorageResponse(this);
    }

    /// <summary>Field number for the "Storage" field.</summary>
    public const int StorageFieldNumber = 1;
    private global::EtAlii.Ubigia.Api.Transport.Management.Grpc.Storage storage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EtAlii.Ubigia.Api.Transport.Management.Grpc.Storage Storage {
      get { return storage_; }
      set {
        storage_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StorageResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StorageResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Storage, other.Storage)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (storage_ != null) hash ^= Storage.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (storage_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Storage);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (storage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Storage);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StorageResponse other) {
      if (other == null) {
        return;
      }
      if (other.storage_ != null) {
        if (storage_ == null) {
          storage_ = new global::EtAlii.Ubigia.Api.Transport.Management.Grpc.Storage();
        }
        Storage.MergeFrom(other.Storage);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (storage_ == null) {
              storage_ = new global::EtAlii.Ubigia.Api.Transport.Management.Grpc.Storage();
            }
            input.ReadMessage(storage_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
