// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Storage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol {

  /// <summary>Holder for reflection information generated from Storage.proto</summary>
  public static partial class StorageReflection {

    #region Descriptor
    /// <summary>File descriptor for Storage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StorageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1TdG9yYWdlLnByb3RvEjhFdEFsaWkuVWJpZ2lhLkFwaS5UcmFuc3BvcnQu",
            "TWFuYWdlbWVudC5HcnBjLldpcmVQcm90b2NvbBoMX01vZGVsLnByb3RvItcB",
            "ChRTdG9yYWdlU2luZ2xlUmVxdWVzdBJMCgJJZBgBIAEoCzI+LkV0QWxpaS5V",
            "YmlnaWEuQXBpLlRyYW5zcG9ydC5NYW5hZ2VtZW50LkdycGMuV2lyZVByb3Rv",
            "Y29sLkd1aWRIABIOCgROYW1lGAIgASgJSAASVAoHU3RvcmFnZRgDIAEoCzJB",
            "LkV0QWxpaS5VYmlnaWEuQXBpLlRyYW5zcG9ydC5NYW5hZ2VtZW50LkdycGMu",
            "V2lyZVByb3RvY29sLlN0b3JhZ2VIAEILCglTZWxlY3Rpb24iGAoWU3RvcmFn",
            "ZU11bHRpcGxlUmVxdWVzdCJrChVTdG9yYWdlU2luZ2xlUmVzcG9uc2USUgoH",
            "U3RvcmFnZRgBIAEoCzJBLkV0QWxpaS5VYmlnaWEuQXBpLlRyYW5zcG9ydC5N",
            "YW5hZ2VtZW50LkdycGMuV2lyZVByb3RvY29sLlN0b3JhZ2UibgoXU3RvcmFn",
            "ZU11bHRpcGxlUmVzcG9uc2USUwoIU3RvcmFnZXMYASADKAsyQS5FdEFsaWku",
            "VWJpZ2lhLkFwaS5UcmFuc3BvcnQuTWFuYWdlbWVudC5HcnBjLldpcmVQcm90",
            "b2NvbC5TdG9yYWdlMrEIChJTdG9yYWdlR3JwY1NlcnZpY2USrgEKCUdldFNp",
            "bmdsZRJOLkV0QWxpaS5VYmlnaWEuQXBpLlRyYW5zcG9ydC5NYW5hZ2VtZW50",
            "LkdycGMuV2lyZVByb3RvY29sLlN0b3JhZ2VTaW5nbGVSZXF1ZXN0Gk8uRXRB",
            "bGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0Lk1hbmFnZW1lbnQuR3JwYy5XaXJl",
            "UHJvdG9jb2wuU3RvcmFnZVNpbmdsZVJlc3BvbnNlIgAStAEKC0dldE11bHRp",
            "cGxlElAuRXRBbGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0Lk1hbmFnZW1lbnQu",
            "R3JwYy5XaXJlUHJvdG9jb2wuU3RvcmFnZU11bHRpcGxlUmVxdWVzdBpRLkV0",
            "QWxpaS5VYmlnaWEuQXBpLlRyYW5zcG9ydC5NYW5hZ2VtZW50LkdycGMuV2ly",
            "ZVByb3RvY29sLlN0b3JhZ2VNdWx0aXBsZVJlc3BvbnNlIgASrQEKCEdldExv",
            "Y2FsEk4uRXRBbGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0Lk1hbmFnZW1lbnQu",
            "R3JwYy5XaXJlUHJvdG9jb2wuU3RvcmFnZVNpbmdsZVJlcXVlc3QaTy5FdEFs",
            "aWkuVWJpZ2lhLkFwaS5UcmFuc3BvcnQuTWFuYWdlbWVudC5HcnBjLldpcmVQ",
            "cm90b2NvbC5TdG9yYWdlU2luZ2xlUmVzcG9uc2UiABKpAQoEUG9zdBJOLkV0",
            "QWxpaS5VYmlnaWEuQXBpLlRyYW5zcG9ydC5NYW5hZ2VtZW50LkdycGMuV2ly",
            "ZVByb3RvY29sLlN0b3JhZ2VTaW5nbGVSZXF1ZXN0Gk8uRXRBbGlpLlViaWdp",
            "YS5BcGkuVHJhbnNwb3J0Lk1hbmFnZW1lbnQuR3JwYy5XaXJlUHJvdG9jb2wu",
            "U3RvcmFnZVNpbmdsZVJlc3BvbnNlIgASqAEKA1B1dBJOLkV0QWxpaS5VYmln",
            "aWEuQXBpLlRyYW5zcG9ydC5NYW5hZ2VtZW50LkdycGMuV2lyZVByb3RvY29s",
            "LlN0b3JhZ2VTaW5nbGVSZXF1ZXN0Gk8uRXRBbGlpLlViaWdpYS5BcGkuVHJh",
            "bnNwb3J0Lk1hbmFnZW1lbnQuR3JwYy5XaXJlUHJvdG9jb2wuU3RvcmFnZVNp",
            "bmdsZVJlc3BvbnNlIgASqwEKBkRlbGV0ZRJOLkV0QWxpaS5VYmlnaWEuQXBp",
            "LlRyYW5zcG9ydC5NYW5hZ2VtZW50LkdycGMuV2lyZVByb3RvY29sLlN0b3Jh",
            "Z2VTaW5nbGVSZXF1ZXN0Gk8uRXRBbGlpLlViaWdpYS5BcGkuVHJhbnNwb3J0",
            "Lk1hbmFnZW1lbnQuR3JwYy5XaXJlUHJvdG9jb2wuU3RvcmFnZVNpbmdsZVJl",
            "c3BvbnNlIgBCiAEKOEV0QWxpaS5VYmlnaWEuQXBpLlRyYW5zcG9ydC5NYW5h",
            "Z2VtZW50LkdycGMuV2lyZVByb3RvY29sQgZVYmlnaWFQAaICBlViaWdpYaoC",
            "OEV0QWxpaS5VYmlnaWEuQXBpLlRyYW5zcG9ydC5NYW5hZ2VtZW50LkdycGMu",
            "V2lyZVByb3RvY29sYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.ModelReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest), global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleRequest.Parser, new[]{ "Id", "Name", "Storage" }, new[]{ "Selection" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleRequest), global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleRequest.Parser, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse), global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageSingleResponse.Parser, new[]{ "Storage" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleResponse), global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageMultipleResponse.Parser, new[]{ "Storages" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class StorageSingleRequest : pb::IMessage<StorageSingleRequest> {
    private static readonly pb::MessageParser<StorageSingleRequest> _parser = new pb::MessageParser<StorageSingleRequest>(() => new StorageSingleRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StorageSingleRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageSingleRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageSingleRequest(StorageSingleRequest other) : this() {
      switch (other.SelectionCase) {
        case SelectionOneofCase.Id:
          Id = other.Id.Clone();
          break;
        case SelectionOneofCase.Name:
          Name = other.Name;
          break;
        case SelectionOneofCase.Storage:
          Storage = other.Storage.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageSingleRequest Clone() {
      return new StorageSingleRequest(this);
    }

    /// <summary>Field number for the "Id" field.</summary>
    public const int IdFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Guid Id {
      get { return selectionCase_ == SelectionOneofCase.Id ? (global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Guid) selection_ : null; }
      set {
        selection_ = value;
        selectionCase_ = value == null ? SelectionOneofCase.None : SelectionOneofCase.Id;
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return selectionCase_ == SelectionOneofCase.Name ? (string) selection_ : ""; }
      set {
        selection_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        selectionCase_ = SelectionOneofCase.Name;
      }
    }

    /// <summary>Field number for the "Storage" field.</summary>
    public const int StorageFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage Storage {
      get { return selectionCase_ == SelectionOneofCase.Storage ? (global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage) selection_ : null; }
      set {
        selection_ = value;
        selectionCase_ = value == null ? SelectionOneofCase.None : SelectionOneofCase.Storage;
      }
    }

    private object selection_;
    /// <summary>Enum of possible cases for the "Selection" oneof.</summary>
    public enum SelectionOneofCase {
      None = 0,
      Id = 1,
      Name = 2,
      Storage = 3,
    }
    private SelectionOneofCase selectionCase_ = SelectionOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SelectionOneofCase SelectionCase {
      get { return selectionCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSelection() {
      selectionCase_ = SelectionOneofCase.None;
      selection_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StorageSingleRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StorageSingleRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Id, other.Id)) return false;
      if (Name != other.Name) return false;
      if (!object.Equals(Storage, other.Storage)) return false;
      if (SelectionCase != other.SelectionCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (selectionCase_ == SelectionOneofCase.Id) hash ^= Id.GetHashCode();
      if (selectionCase_ == SelectionOneofCase.Name) hash ^= Name.GetHashCode();
      if (selectionCase_ == SelectionOneofCase.Storage) hash ^= Storage.GetHashCode();
      hash ^= (int) selectionCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (selectionCase_ == SelectionOneofCase.Id) {
        output.WriteRawTag(10);
        output.WriteMessage(Id);
      }
      if (selectionCase_ == SelectionOneofCase.Name) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (selectionCase_ == SelectionOneofCase.Storage) {
        output.WriteRawTag(26);
        output.WriteMessage(Storage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (selectionCase_ == SelectionOneofCase.Id) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Id);
      }
      if (selectionCase_ == SelectionOneofCase.Name) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (selectionCase_ == SelectionOneofCase.Storage) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Storage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StorageSingleRequest other) {
      if (other == null) {
        return;
      }
      switch (other.SelectionCase) {
        case SelectionOneofCase.Id:
          if (Id == null) {
            Id = new global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Guid();
          }
          Id.MergeFrom(other.Id);
          break;
        case SelectionOneofCase.Name:
          Name = other.Name;
          break;
        case SelectionOneofCase.Storage:
          if (Storage == null) {
            Storage = new global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage();
          }
          Storage.MergeFrom(other.Storage);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Guid subBuilder = new global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Guid();
            if (selectionCase_ == SelectionOneofCase.Id) {
              subBuilder.MergeFrom(Id);
            }
            input.ReadMessage(subBuilder);
            Id = subBuilder;
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage subBuilder = new global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage();
            if (selectionCase_ == SelectionOneofCase.Storage) {
              subBuilder.MergeFrom(Storage);
            }
            input.ReadMessage(subBuilder);
            Storage = subBuilder;
            break;
          }
        }
      }
    }

  }

  public sealed partial class StorageMultipleRequest : pb::IMessage<StorageMultipleRequest> {
    private static readonly pb::MessageParser<StorageMultipleRequest> _parser = new pb::MessageParser<StorageMultipleRequest>(() => new StorageMultipleRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StorageMultipleRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageMultipleRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageMultipleRequest(StorageMultipleRequest other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageMultipleRequest Clone() {
      return new StorageMultipleRequest(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StorageMultipleRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StorageMultipleRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StorageMultipleRequest other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class StorageSingleResponse : pb::IMessage<StorageSingleResponse> {
    private static readonly pb::MessageParser<StorageSingleResponse> _parser = new pb::MessageParser<StorageSingleResponse>(() => new StorageSingleResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StorageSingleResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageSingleResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageSingleResponse(StorageSingleResponse other) : this() {
      storage_ = other.storage_ != null ? other.storage_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageSingleResponse Clone() {
      return new StorageSingleResponse(this);
    }

    /// <summary>Field number for the "Storage" field.</summary>
    public const int StorageFieldNumber = 1;
    private global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage storage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage Storage {
      get { return storage_; }
      set {
        storage_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StorageSingleResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StorageSingleResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Storage, other.Storage)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (storage_ != null) hash ^= Storage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (storage_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Storage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (storage_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Storage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StorageSingleResponse other) {
      if (other == null) {
        return;
      }
      if (other.storage_ != null) {
        if (storage_ == null) {
          Storage = new global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage();
        }
        Storage.MergeFrom(other.Storage);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (storage_ == null) {
              Storage = new global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage();
            }
            input.ReadMessage(Storage);
            break;
          }
        }
      }
    }

  }

  public sealed partial class StorageMultipleResponse : pb::IMessage<StorageMultipleResponse> {
    private static readonly pb::MessageParser<StorageMultipleResponse> _parser = new pb::MessageParser<StorageMultipleResponse>(() => new StorageMultipleResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<StorageMultipleResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.StorageReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageMultipleResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageMultipleResponse(StorageMultipleResponse other) : this() {
      storages_ = other.storages_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public StorageMultipleResponse Clone() {
      return new StorageMultipleResponse(this);
    }

    /// <summary>Field number for the "Storages" field.</summary>
    public const int StoragesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage> _repeated_storages_codec
        = pb::FieldCodec.ForMessage(10, global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage.Parser);
    private readonly pbc::RepeatedField<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage> storages_ = new pbc::RepeatedField<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::EtAlii.Ubigia.Api.Transport.Management.Grpc.WireProtocol.Storage> Storages {
      get { return storages_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as StorageMultipleResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(StorageMultipleResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!storages_.Equals(other.storages_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= storages_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      storages_.WriteTo(output, _repeated_storages_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += storages_.CalculateSize(_repeated_storages_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(StorageMultipleResponse other) {
      if (other == null) {
        return;
      }
      storages_.Add(other.storages_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            storages_.AddEntriesFrom(input, _repeated_storages_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
